import ts from "typescript";

export const generateEnumExports = (source: string): string => {
  const sourceFile = ts.createSourceFile(
    "generated.ts",
    source,
    ts.ScriptTarget.Latest,
    true,
  );
  const enumNames = sourceFile.statements
    .filter(ts.isEnumDeclaration)
    .filter((declaration) =>
      declaration.modifiers?.some(
        ({ kind }) => kind === ts.SyntaxKind.ExportKeyword,
      ),
    )
    .map(({ name }) => name.text)
    .sort();

  return [
    "/* This file was generated by `yarn gen-clients`. Don't edit it directly */",
    ...(enumNames.length > 0
      ? [`export { ${enumNames.join(", ")} } from "../generated/generated.js";`]
      : []),
    'export type * from "../generated/generated.js";',
  ].join("\n");
};
