import { writeFileSync } from "fs";
import path from "path";

import { generate } from "@graphql-codegen/cli";
import type { Types } from "@graphql-codegen/plugin-helpers";
import prettier from "prettier";

const GENERATED_FILENAME = "generated/generated.ts";

generate(
  {
    schema: "https://api.us-west-2.fragment.dev/schema.graphql",
    emitLegacyCommonJSImports: false,
    generates: {
      [GENERATED_FILENAME]: {
        documents: "src/queries/**/*.graphql",
        config: {
          scalars: {
            ID: "string",
            JSON: "Record<string, unknown>",
          },
          withHooks: true,
          defaultScalarType: "string",
          useImplementingTypes: true,
          // codegen v7's typescript-operations emits schema enums/inputs itself,
          // which duplicates the typescript plugin. Pointing it at a "shared types"
          // module suppresses that; the self-import and namespace are stripped below
          // so the output stays a single flat file.
          importSchemaTypesFrom: "./generated.js",
          namespacedImportName: "Types",
          // v7 stops emitting __typename in operation types by default; restore it.
          addTypename: true,
          nonOptionalTypename: true,
        },
        plugins: [
          "typescript",
          "typescript-operations",
          "typescript-graphql-request",
          {
            add: {
              content:
                "/* This file was generated by `yarn gen-clients`. Don't edit it directly */ \n/* eslint-disable @typescript-eslint/no-explicit-any */",
            },
          },
        ],
      },
    },
  },
  false,
)
  .then(async ([fileOutput]: Types.FileOutput[]) => {
    const output = fileOutput.content
      .replace(/import gql from 'graphql-tag'/g, "import { gql } from 'graphql-tag'")
      .replace(/^import type \* as Types from '[^']*generated\.js';\n/m, "")
      .replace(/\bTypes\./g, "")
      // v7 no longer exports these codegen helpers; 1.x consumers could import them.
      .replace(/^type Exact</m, "export type Exact<");

    const compatHelpers = [
      "export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {",
      "  [SubKey in K]?: Maybe<T[SubKey]>;",
      "};",
      "export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {",
      "  [SubKey in K]: Maybe<T[SubKey]>;",
      "};",
      "export type MakeEmpty<",
      "  T extends { [key: string]: unknown },",
      "  K extends keyof T,",
      "> = { [_ in K]?: never };",
    ].join("\n");
    const prettifiedOutput = await prettier.format(output + "\n" + compatHelpers, {
      parser: "typescript",
    });
    const qualifiedFilename = path.resolve(process.cwd(), fileOutput.filename);
    writeFileSync(qualifiedFilename, prettifiedOutput, "utf-8");
    process.exit(0);
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
