import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "https://api.fragment.dev/schema.graphql",
  emitLegacyCommonJSImports: false,
  generates: {
    "generated/generated.ts": {
      config: {
        scalars: {
          ID: "string",
          JSON: "Record<string, unknown>",
        },
        withHooks: true,
        defaultScalarType: "string",
        useImplementingTypes: true,
      },
      documents: "src/queries/**/*.graphql",
      hooks: {
        afterOneFileWrite: [
          `sed -i '' "s/import gql from 'graphql-tag'/import { gql } from 'graphql-tag'/"`,
          "prettier --write",
        ],
      },
      plugins: [
        "typescript",
        "typescript-operations",
        "typescript-graphql-request",
        {
          add: {
            content:
              "/* This file was generated by `yarn gen-clients`. Don't edit it directly */ \n/* eslint-disable @typescript-eslint/no-explicit-any */",
          },
        },
      ],
    },
  },
};

export default config;
