name: Publish Package to npmjs
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2
        id: generate-token
        with:
          app-id: ${{ secrets.PR_APP_ID }}
          private-key: ${{ secrets.PR_APP_PRIVATE_KEY }}

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        name: Checkout repository

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        name: Use Node.js 24.x
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@fragment-dev'

      - name: Install dependencies
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
        with:
          retry_on: error
          timeout_minutes: 5
          max_attempts: 2
          command: yarn

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
